/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedKioskRouteImport } from './routes/_authenticated/kiosk'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedQcRouteImport } from './routes/_authenticated/qc'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedWarrantyRouteImport } from './routes/_authenticated/warranty'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedSalesDealIdRouteImport } from './routes/_authenticated/sales.$dealId'
import { Route as ApiPublicSyncDrainRouteImport } from './routes/api/public/sync-drain'
import { Route as OauthConnectorReturnRouteImport } from './routes/oauth/connector/return'
import { Route as OauthHubspotReturnRouteImport } from './routes/oauth/hubspot/return'
import { Route as OauthQuickbooksReturnRouteImport } from './routes/oauth/quickbooks/return'
import { Route as PProposalTokenRouteImport } from './routes/p/proposal.$token'
import { Route as PWaiverTokenRouteImport } from './routes/p/waiver.$token'
import { Route as PWarrantyTokenRouteImport } from './routes/p/warranty.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKioskRoute = AuthenticatedKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQcRoute = AuthenticatedQcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarrantyRoute = AuthenticatedWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesDealIdRoute =
  AuthenticatedSalesDealIdRouteImport.update({
    id: '/sales/$dealId',
    path: '/sales/$dealId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSyncDrainRoute = ApiPublicSyncDrainRouteImport.update({
  id: '/api/public/sync-drain',
  path: '/api/public/sync-drain',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConnectorReturnRoute = OauthConnectorReturnRouteImport.update({
  id: '/oauth/connector/return',
  path: '/oauth/connector/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthHubspotReturnRoute = OauthHubspotReturnRouteImport.update({
  id: '/oauth/hubspot/return',
  path: '/oauth/hubspot/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthQuickbooksReturnRoute = OauthQuickbooksReturnRouteImport.update({
  id: '/oauth/quickbooks/return',
  path: '/oauth/quickbooks/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PProposalTokenRoute = PProposalTokenRouteImport.update({
  id: '/p/proposal/$token',
  path: '/p/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PWaiverTokenRoute = PWaiverTokenRouteImport.update({
  id: '/p/waiver/$token',
  path: '/p/waiver/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PWarrantyTokenRoute = PWarrantyTokenRouteImport.update({
  id: '/p/warranty/$token',
  path: '/p/warranty/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/platform': typeof PlatformRoute
  '/workflow': typeof WorkflowRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/kiosk': typeof AuthenticatedKioskRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/qc': typeof AuthenticatedQcRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/warranty': typeof AuthenticatedWarrantyRoute
  '/sales/$dealId': typeof AuthenticatedSalesDealIdRoute
  '/api/public/sync-drain': typeof ApiPublicSyncDrainRoute
  '/oauth/connector/return': typeof OauthConnectorReturnRoute
  '/oauth/hubspot/return': typeof OauthHubspotReturnRoute
  '/oauth/quickbooks/return': typeof OauthQuickbooksReturnRoute
  '/p/proposal/$token': typeof PProposalTokenRoute
  '/p/waiver/$token': typeof PWaiverTokenRoute
  '/p/warranty/$token': typeof PWarrantyTokenRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/platform': typeof PlatformRoute
  '/workflow': typeof WorkflowRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/kiosk': typeof AuthenticatedKioskRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/qc': typeof AuthenticatedQcRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/warranty': typeof AuthenticatedWarrantyRoute
  '/sales/$dealId': typeof AuthenticatedSalesDealIdRoute
  '/api/public/sync-drain': typeof ApiPublicSyncDrainRoute
  '/oauth/connector/return': typeof OauthConnectorReturnRoute
  '/oauth/hubspot/return': typeof OauthHubspotReturnRoute
  '/oauth/quickbooks/return': typeof OauthQuickbooksReturnRoute
  '/p/proposal/$token': typeof PProposalTokenRoute
  '/p/waiver/$token': typeof PWaiverTokenRoute
  '/p/warranty/$token': typeof PWarrantyTokenRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/platform': typeof PlatformRoute
  '/workflow': typeof WorkflowRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/kiosk': typeof AuthenticatedKioskRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/qc': typeof AuthenticatedQcRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/warranty': typeof AuthenticatedWarrantyRoute
  '/_authenticated/sales/$dealId': typeof AuthenticatedSalesDealIdRoute
  '/api/public/sync-drain': typeof ApiPublicSyncDrainRoute
  '/oauth/connector/return': typeof OauthConnectorReturnRoute
  '/oauth/hubspot/return': typeof OauthHubspotReturnRoute
  '/oauth/quickbooks/return': typeof OauthQuickbooksReturnRoute
  '/p/proposal/$token': typeof PProposalTokenRoute
  '/p/waiver/$token': typeof PWaiverTokenRoute
  '/p/warranty/$token': typeof PWarrantyTokenRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connect'
    | '/demo'
    | '/platform'
    | '/workflow'
    | '/analytics'
    | '/automations'
    | '/command-center'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/inspections'
    | '/integrations'
    | '/inventory'
    | '/jobs'
    | '/kiosk'
    | '/packages'
    | '/payments'
    | '/qc'
    | '/schedule'
    | '/services'
    | '/settings'
    | '/team'
    | '/vehicles'
    | '/warranty'
    | '/sales/$dealId'
    | '/api/public/sync-drain'
    | '/oauth/connector/return'
    | '/oauth/hubspot/return'
    | '/oauth/quickbooks/return'
    | '/p/proposal/$token'
    | '/p/waiver/$token'
    | '/p/warranty/$token'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connect'
    | '/demo'
    | '/platform'
    | '/workflow'
    | '/analytics'
    | '/automations'
    | '/command-center'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/inspections'
    | '/integrations'
    | '/inventory'
    | '/jobs'
    | '/kiosk'
    | '/packages'
    | '/payments'
    | '/qc'
    | '/schedule'
    | '/services'
    | '/settings'
    | '/team'
    | '/vehicles'
    | '/warranty'
    | '/sales/$dealId'
    | '/api/public/sync-drain'
    | '/oauth/connector/return'
    | '/oauth/hubspot/return'
    | '/oauth/quickbooks/return'
    | '/p/proposal/$token'
    | '/p/waiver/$token'
    | '/p/warranty/$token'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/connect'
    | '/demo'
    | '/platform'
    | '/workflow'
    | '/_authenticated/analytics'
    | '/_authenticated/automations'
    | '/_authenticated/command-center'
    | '/_authenticated/customers'
    | '/_authenticated/documents'
    | '/_authenticated/estimates'
    | '/_authenticated/inspections'
    | '/_authenticated/integrations'
    | '/_authenticated/inventory'
    | '/_authenticated/jobs'
    | '/_authenticated/kiosk'
    | '/_authenticated/packages'
    | '/_authenticated/payments'
    | '/_authenticated/qc'
    | '/_authenticated/schedule'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/vehicles'
    | '/_authenticated/warranty'
    | '/_authenticated/sales/$dealId'
    | '/api/public/sync-drain'
    | '/oauth/connector/return'
    | '/oauth/hubspot/return'
    | '/oauth/quickbooks/return'
    | '/p/proposal/$token'
    | '/p/waiver/$token'
    | '/p/warranty/$token'
    | '/_authenticated/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  DemoRoute: typeof DemoRoute
  PlatformRoute: typeof PlatformRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiPublicSyncDrainRoute: typeof ApiPublicSyncDrainRoute
  OauthConnectorReturnRoute: typeof OauthConnectorReturnRoute
  OauthHubspotReturnRoute: typeof OauthHubspotReturnRoute
  OauthQuickbooksReturnRoute: typeof OauthQuickbooksReturnRoute
  PProposalTokenRoute: typeof PProposalTokenRoute
  PWaiverTokenRoute: typeof PWaiverTokenRoute
  PWarrantyTokenRoute: typeof PWarrantyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kiosk': {
      id: '/_authenticated/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AuthenticatedKioskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qc': {
      id: '/_authenticated/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof AuthenticatedQcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warranty': {
      id: '/_authenticated/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof AuthenticatedWarrantyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/$dealId': {
      id: '/_authenticated/sales/$dealId'
      path: '/sales/$dealId'
      fullPath: '/sales/$dealId'
      preLoaderRoute: typeof AuthenticatedSalesDealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync-drain': {
      id: '/api/public/sync-drain'
      path: '/api/public/sync-drain'
      fullPath: '/api/public/sync-drain'
      preLoaderRoute: typeof ApiPublicSyncDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/connector/return': {
      id: '/oauth/connector/return'
      path: '/oauth/connector/return'
      fullPath: '/oauth/connector/return'
      preLoaderRoute: typeof OauthConnectorReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/hubspot/return': {
      id: '/oauth/hubspot/return'
      path: '/oauth/hubspot/return'
      fullPath: '/oauth/hubspot/return'
      preLoaderRoute: typeof OauthHubspotReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/quickbooks/return': {
      id: '/oauth/quickbooks/return'
      path: '/oauth/quickbooks/return'
      fullPath: '/oauth/quickbooks/return'
      preLoaderRoute: typeof OauthQuickbooksReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/proposal/$token': {
      id: '/p/proposal/$token'
      path: '/p/proposal/$token'
      fullPath: '/p/proposal/$token'
      preLoaderRoute: typeof PProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/waiver/$token': {
      id: '/p/waiver/$token'
      path: '/p/waiver/$token'
      fullPath: '/p/waiver/$token'
      preLoaderRoute: typeof PWaiverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/warranty/$token': {
      id: '/p/warranty/$token'
      path: '/p/warranty/$token'
      fullPath: '/p/warranty/$token'
      preLoaderRoute: typeof PWarrantyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedKioskRoute: typeof AuthenticatedKioskRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedQcRoute: typeof AuthenticatedQcRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedWarrantyRoute: typeof AuthenticatedWarrantyRoute
  AuthenticatedSalesDealIdRoute: typeof AuthenticatedSalesDealIdRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedKioskRoute: AuthenticatedKioskRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedQcRoute: AuthenticatedQcRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedWarrantyRoute: AuthenticatedWarrantyRoute,
  AuthenticatedSalesDealIdRoute: AuthenticatedSalesDealIdRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  DemoRoute: DemoRoute,
  PlatformRoute: PlatformRoute,
  WorkflowRoute: WorkflowRoute,
  ApiPublicSyncDrainRoute: ApiPublicSyncDrainRoute,
  OauthConnectorReturnRoute: OauthConnectorReturnRoute,
  OauthHubspotReturnRoute: OauthHubspotReturnRoute,
  OauthQuickbooksReturnRoute: OauthQuickbooksReturnRoute,
  PProposalTokenRoute: PProposalTokenRoute,
  PWaiverTokenRoute: PWaiverTokenRoute,
  PWarrantyTokenRoute: PWarrantyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
