/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedCorporateRouteImport } from './routes/_authenticated/corporate'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedFilmsRouteImport } from './routes/_authenticated/films'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedKioskRouteImport } from './routes/_authenticated/kiosk'
import { Route as AuthenticatedMobileRouteImport } from './routes/_authenticated/mobile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedQcRouteImport } from './routes/_authenticated/qc'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedVehicleIntelRouteImport } from './routes/_authenticated/vehicle-intel'
import { Route as AuthenticatedWarrantyRouteImport } from './routes/_authenticated/warranty'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations.index'
import { Route as AuthenticatedAutomationsWorkflowIdRouteImport } from './routes/_authenticated/automations.$workflowId'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedSalesDealIdRouteImport } from './routes/_authenticated/sales.$dealId'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales.new'
import { Route as ApiPublicSyncDrainRouteImport } from './routes/api/public/sync-drain'
import { Route as OauthConnectorReturnRouteImport } from './routes/oauth/connector/return'
import { Route as OauthHubspotReturnRouteImport } from './routes/oauth/hubspot/return'
import { Route as OauthQuickbooksReturnRouteImport } from './routes/oauth/quickbooks/return'
import { Route as PPortalTokenRouteImport } from './routes/p/portal.$token'
import { Route as PProposalTokenRouteImport } from './routes/p/proposal.$token'
import { Route as PWaiverTokenRouteImport } from './routes/p/waiver.$token'
import { Route as PWarrantyTokenRouteImport } from './routes/p/warranty.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorporateRoute = AuthenticatedCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmsRoute = AuthenticatedFilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKioskRoute = AuthenticatedKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMobileRoute = AuthenticatedMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQcRoute = AuthenticatedQcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehicleIntelRoute =
  AuthenticatedVehicleIntelRouteImport.update({
    id: '/vehicle-intel',
    path: '/vehicle-intel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWarrantyRoute = AuthenticatedWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsWorkflowIdRoute =
  AuthenticatedAutomationsWorkflowIdRouteImport.update({
    id: '/automations/$workflowId',
    path: '/automations/$workflowId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesDealIdRoute =
  AuthenticatedSalesDealIdRouteImport.update({
    id: '/sales/$dealId',
    path: '/sales/$dealId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSyncDrainRoute = ApiPublicSyncDrainRouteImport.update({
  id: '/api/public/sync-drain',
  path: '/api/public/sync-drain',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConnectorReturnRoute = OauthConnectorReturnRouteImport.update({
  id: '/oauth/connector/return',
  path: '/oauth/connector/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthHubspotReturnRoute = OauthHubspotReturnRouteImport.update({
  id: '/oauth/hubspot/return',
  path: '/oauth/hubspot/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthQuickbooksReturnRoute = OauthQuickbooksReturnRouteImport.update({
  id: '/oauth/quickbooks/return',
  path: '/oauth/quickbooks/return',
  getParentRoute: () => rootRouteImport,
} as any)
const PPortalTokenRoute = PPortalTokenRouteImport.update({
  id: '/p/portal/$token',
  path: '/p/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PProposalTokenRoute = PProposalTokenRouteImport.update({
  id: '/p/proposal/$token',
  path: '/p/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PWaiverTokenRoute = PWaiverTokenRouteImport.update({
  id: '/p/waiver/$token',
  path: '/p/waiver/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PWarrantyTokenRoute = PWarrantyTokenRouteImport.update({
  id: '/p/warranty/$token',
  path: '/p/warranty/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/workflow': typeof WorkflowRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/corporate': typeof AuthenticatedCorporateRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/films': typeof AuthenticatedFilmsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/import': typeof AuthenticatedImportRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/kiosk': typeof AuthenticatedKioskRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/qc': typeof AuthenticatedQcRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/team': typeof AuthenticatedTeamRoute
  '/vehicle-intel': typeof AuthenticatedVehicleIntelRoute
  '/warranty': typeof AuthenticatedWarrantyRoute
  '/automations/$workflowId': typeof AuthenticatedAutomationsWorkflowIdRoute
  '/sales/$dealId': typeof AuthenticatedSalesDealIdRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/api/public/sync-drain': typeof ApiPublicSyncDrainRoute
  '/oauth/connector/return': typeof OauthConnectorReturnRoute
  '/oauth/hubspot/return': typeof OauthHubspotReturnRoute
  '/oauth/quickbooks/return': typeof OauthQuickbooksReturnRoute
  '/p/portal/$token': typeof PPortalTokenRoute
  '/p/proposal/$token': typeof PProposalTokenRoute
  '/p/waiver/$token': typeof PWaiverTokenRoute
  '/p/warranty/$token': typeof PWarrantyTokenRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/workflow': typeof WorkflowRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/corporate': typeof AuthenticatedCorporateRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/films': typeof AuthenticatedFilmsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/import': typeof AuthenticatedImportRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/kiosk': typeof AuthenticatedKioskRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/qc': typeof AuthenticatedQcRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/team': typeof AuthenticatedTeamRoute
  '/vehicle-intel': typeof AuthenticatedVehicleIntelRoute
  '/warranty': typeof AuthenticatedWarrantyRoute
  '/automations/$workflowId': typeof AuthenticatedAutomationsWorkflowIdRoute
  '/sales/$dealId': typeof AuthenticatedSalesDealIdRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/api/public/sync-drain': typeof ApiPublicSyncDrainRoute
  '/oauth/connector/return': typeof OauthConnectorReturnRoute
  '/oauth/hubspot/return': typeof OauthHubspotReturnRoute
  '/oauth/quickbooks/return': typeof OauthQuickbooksReturnRoute
  '/p/portal/$token': typeof PPortalTokenRoute
  '/p/proposal/$token': typeof PProposalTokenRoute
  '/p/waiver/$token': typeof PWaiverTokenRoute
  '/p/warranty/$token': typeof PWarrantyTokenRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/platform': typeof PlatformRoute
  '/workflow': typeof WorkflowRoute
  '/_authenticated/agency': typeof AuthenticatedAgencyRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/corporate': typeof AuthenticatedCorporateRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/films': typeof AuthenticatedFilmsRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/kiosk': typeof AuthenticatedKioskRoute
  '/_authenticated/mobile': typeof AuthenticatedMobileRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/qc': typeof AuthenticatedQcRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/vehicle-intel': typeof AuthenticatedVehicleIntelRoute
  '/_authenticated/warranty': typeof AuthenticatedWarrantyRoute
  '/_authenticated/automations/$workflowId': typeof AuthenticatedAutomationsWorkflowIdRoute
  '/_authenticated/sales/$dealId': typeof AuthenticatedSalesDealIdRoute
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/api/public/sync-drain': typeof ApiPublicSyncDrainRoute
  '/oauth/connector/return': typeof OauthConnectorReturnRoute
  '/oauth/hubspot/return': typeof OauthHubspotReturnRoute
  '/oauth/quickbooks/return': typeof OauthQuickbooksReturnRoute
  '/p/portal/$token': typeof PPortalTokenRoute
  '/p/proposal/$token': typeof PProposalTokenRoute
  '/p/waiver/$token': typeof PWaiverTokenRoute
  '/p/warranty/$token': typeof PWarrantyTokenRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/connect'
    | '/demo'
    | '/faq'
    | '/platform'
    | '/workflow'
    | '/agency'
    | '/analytics'
    | '/audit'
    | '/calendar'
    | '/campaigns'
    | '/command-center'
    | '/commissions'
    | '/corporate'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/films'
    | '/follow-ups'
    | '/gallery'
    | '/import'
    | '/inbox'
    | '/inspections'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/kiosk'
    | '/mobile'
    | '/payments'
    | '/qc'
    | '/schedule'
    | '/services'
    | '/settings'
    | '/setup'
    | '/team'
    | '/vehicle-intel'
    | '/warranty'
    | '/automations/$workflowId'
    | '/sales/$dealId'
    | '/sales/new'
    | '/api/public/sync-drain'
    | '/oauth/connector/return'
    | '/oauth/hubspot/return'
    | '/oauth/quickbooks/return'
    | '/p/portal/$token'
    | '/p/proposal/$token'
    | '/p/waiver/$token'
    | '/p/warranty/$token'
    | '/automations/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/connect'
    | '/demo'
    | '/faq'
    | '/platform'
    | '/workflow'
    | '/agency'
    | '/analytics'
    | '/audit'
    | '/calendar'
    | '/campaigns'
    | '/command-center'
    | '/commissions'
    | '/corporate'
    | '/customers'
    | '/documents'
    | '/estimates'
    | '/films'
    | '/follow-ups'
    | '/gallery'
    | '/import'
    | '/inbox'
    | '/inspections'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/kiosk'
    | '/mobile'
    | '/payments'
    | '/qc'
    | '/schedule'
    | '/services'
    | '/settings'
    | '/setup'
    | '/team'
    | '/vehicle-intel'
    | '/warranty'
    | '/automations/$workflowId'
    | '/sales/$dealId'
    | '/sales/new'
    | '/api/public/sync-drain'
    | '/oauth/connector/return'
    | '/oauth/hubspot/return'
    | '/oauth/quickbooks/return'
    | '/p/portal/$token'
    | '/p/proposal/$token'
    | '/p/waiver/$token'
    | '/p/warranty/$token'
    | '/automations'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/connect'
    | '/demo'
    | '/faq'
    | '/platform'
    | '/workflow'
    | '/_authenticated/agency'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/calendar'
    | '/_authenticated/campaigns'
    | '/_authenticated/command-center'
    | '/_authenticated/commissions'
    | '/_authenticated/corporate'
    | '/_authenticated/customers'
    | '/_authenticated/documents'
    | '/_authenticated/estimates'
    | '/_authenticated/films'
    | '/_authenticated/follow-ups'
    | '/_authenticated/gallery'
    | '/_authenticated/import'
    | '/_authenticated/inbox'
    | '/_authenticated/inspections'
    | '/_authenticated/integrations'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/jobs'
    | '/_authenticated/kiosk'
    | '/_authenticated/mobile'
    | '/_authenticated/payments'
    | '/_authenticated/qc'
    | '/_authenticated/schedule'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/team'
    | '/_authenticated/vehicle-intel'
    | '/_authenticated/warranty'
    | '/_authenticated/automations/$workflowId'
    | '/_authenticated/sales/$dealId'
    | '/_authenticated/sales/new'
    | '/api/public/sync-drain'
    | '/oauth/connector/return'
    | '/oauth/hubspot/return'
    | '/oauth/quickbooks/return'
    | '/p/portal/$token'
    | '/p/proposal/$token'
    | '/p/waiver/$token'
    | '/p/warranty/$token'
    | '/_authenticated/automations/'
    | '/_authenticated/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ConnectRoute: typeof ConnectRoute
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  PlatformRoute: typeof PlatformRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiPublicSyncDrainRoute: typeof ApiPublicSyncDrainRoute
  OauthConnectorReturnRoute: typeof OauthConnectorReturnRoute
  OauthHubspotReturnRoute: typeof OauthHubspotReturnRoute
  OauthQuickbooksReturnRoute: typeof OauthQuickbooksReturnRoute
  PPortalTokenRoute: typeof PPortalTokenRoute
  PProposalTokenRoute: typeof PProposalTokenRoute
  PWaiverTokenRoute: typeof PWaiverTokenRoute
  PWarrantyTokenRoute: typeof PWarrantyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corporate': {
      id: '/_authenticated/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof AuthenticatedCorporateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/films': {
      id: '/_authenticated/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof AuthenticatedFilmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kiosk': {
      id: '/_authenticated/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AuthenticatedKioskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile': {
      id: '/_authenticated/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedMobileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qc': {
      id: '/_authenticated/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof AuthenticatedQcRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicle-intel': {
      id: '/_authenticated/vehicle-intel'
      path: '/vehicle-intel'
      fullPath: '/vehicle-intel'
      preLoaderRoute: typeof AuthenticatedVehicleIntelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warranty': {
      id: '/_authenticated/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof AuthenticatedWarrantyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/$workflowId': {
      id: '/_authenticated/automations/$workflowId'
      path: '/automations/$workflowId'
      fullPath: '/automations/$workflowId'
      preLoaderRoute: typeof AuthenticatedAutomationsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/$dealId': {
      id: '/_authenticated/sales/$dealId'
      path: '/sales/$dealId'
      fullPath: '/sales/$dealId'
      preLoaderRoute: typeof AuthenticatedSalesDealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync-drain': {
      id: '/api/public/sync-drain'
      path: '/api/public/sync-drain'
      fullPath: '/api/public/sync-drain'
      preLoaderRoute: typeof ApiPublicSyncDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/connector/return': {
      id: '/oauth/connector/return'
      path: '/oauth/connector/return'
      fullPath: '/oauth/connector/return'
      preLoaderRoute: typeof OauthConnectorReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/hubspot/return': {
      id: '/oauth/hubspot/return'
      path: '/oauth/hubspot/return'
      fullPath: '/oauth/hubspot/return'
      preLoaderRoute: typeof OauthHubspotReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/quickbooks/return': {
      id: '/oauth/quickbooks/return'
      path: '/oauth/quickbooks/return'
      fullPath: '/oauth/quickbooks/return'
      preLoaderRoute: typeof OauthQuickbooksReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/portal/$token': {
      id: '/p/portal/$token'
      path: '/p/portal/$token'
      fullPath: '/p/portal/$token'
      preLoaderRoute: typeof PPortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/proposal/$token': {
      id: '/p/proposal/$token'
      path: '/p/proposal/$token'
      fullPath: '/p/proposal/$token'
      preLoaderRoute: typeof PProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/waiver/$token': {
      id: '/p/waiver/$token'
      path: '/p/waiver/$token'
      fullPath: '/p/waiver/$token'
      preLoaderRoute: typeof PWaiverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/warranty/$token': {
      id: '/p/warranty/$token'
      path: '/p/warranty/$token'
      fullPath: '/p/warranty/$token'
      preLoaderRoute: typeof PWarrantyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedCorporateRoute: typeof AuthenticatedCorporateRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedFilmsRoute: typeof AuthenticatedFilmsRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedKioskRoute: typeof AuthenticatedKioskRoute
  AuthenticatedMobileRoute: typeof AuthenticatedMobileRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedQcRoute: typeof AuthenticatedQcRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedVehicleIntelRoute: typeof AuthenticatedVehicleIntelRoute
  AuthenticatedWarrantyRoute: typeof AuthenticatedWarrantyRoute
  AuthenticatedAutomationsWorkflowIdRoute: typeof AuthenticatedAutomationsWorkflowIdRoute
  AuthenticatedSalesDealIdRoute: typeof AuthenticatedSalesDealIdRoute
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgencyRoute: AuthenticatedAgencyRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedCorporateRoute: AuthenticatedCorporateRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedFilmsRoute: AuthenticatedFilmsRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedKioskRoute: AuthenticatedKioskRoute,
  AuthenticatedMobileRoute: AuthenticatedMobileRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedQcRoute: AuthenticatedQcRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedVehicleIntelRoute: AuthenticatedVehicleIntelRoute,
  AuthenticatedWarrantyRoute: AuthenticatedWarrantyRoute,
  AuthenticatedAutomationsWorkflowIdRoute:
    AuthenticatedAutomationsWorkflowIdRoute,
  AuthenticatedSalesDealIdRoute: AuthenticatedSalesDealIdRoute,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ConnectRoute: ConnectRoute,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  PlatformRoute: PlatformRoute,
  WorkflowRoute: WorkflowRoute,
  ApiPublicSyncDrainRoute: ApiPublicSyncDrainRoute,
  OauthConnectorReturnRoute: OauthConnectorReturnRoute,
  OauthHubspotReturnRoute: OauthHubspotReturnRoute,
  OauthQuickbooksReturnRoute: OauthQuickbooksReturnRoute,
  PPortalTokenRoute: PPortalTokenRoute,
  PProposalTokenRoute: PProposalTokenRoute,
  PWaiverTokenRoute: PWaiverTokenRoute,
  PWarrantyTokenRoute: PWarrantyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
